### ISSUE TITLE
Release on NPM?

### ISSUE THREAD

**Issue by alexdrans** [pagopa/express-azure-functions#5]
Hi, can you release the current version on NPM?

**Comment by gunzip** [comment]
It is already released as a github package. I'd avoid to duplicate this if not required:

https://github.com/pagopa/io-functions-express/packages

**Comment by alexdrans** [comment]
Thanks for this repo!

We, and many others, use the default registry (NPM) for public packages. Would be nice if you could publish it to both, wouldn't want to have to make an exception.
